visualise_fov_cone:
  name: Visualise Field of View Cone
  description: Helper service to more easily configure desired FOV cone. Generates an HTML map file to visualise the configured fov_cone and saves to config/www/community/whats_that_plane/visualise_fov_{location_name}.html.
  fields:
    config_entry_id:
      name: Configuration Entry
      description: The configuration entry to generate the map visualisation for.
      required: true
      selector:
        config_entry:
          integration: whats_that_plane